### ISSUE TITLE
Issues with manual build process

### ISSUE THREAD

**Issue by tomw1994991** [intuit/maven-build-scanner#100]
Hi, 

Wonderful plugin! Really great to see the breakdown of the multi-threaded critical path.

When following the alternative installation steps today I observed the following issues:

- The server was attempting to connect to the mongodb before the db was ready & it crashes silently with an error in the container logs saying that the db connection failed. Workaround is to restart the server container but should it have a 'depends_on' and associated healthcheck in the compose? 
- When running behind a proxy, I had to edit /server/dockerfile to make sure that npm respected the proxy. It does not seem to pick up HTTP_PROXY and HTTPS_PROXY env vars?
-  Had to change the mongodb image to mongo:5.0.5 as the db was exiting with status 62 & printing compatibility messages. 

Did I do something wrong or are these potential tweaks that can be made? Happy to make a PR if so :)

**Comment by alexec** [comment]
No, please raise a PR if you can fix them!
