### ISSUE TITLE
Enable to run "in memory" without mongo

### ISSUE THREAD

**Issue by rmannibucau** [intuit/maven-build-scanner#15]
Would be great to have an in memory datastorage (maybe addressed through http to reuse existing node process?) to light up the infra needed to run the scanner "locally".

**Comment by alexec** [comment]
good idea - would you be interested in creating a PR?

**Comment by rmannibucau** [comment]
@alexec maybe in some times but for now i'm trying to find why I miss some executions in the report (had the same issue with takari plugin)

**Comment by edumco** [comment]
@rmannibucau  is this useful? [https://docs.mongodb.com/manual/core/inmemory/](https://docs.mongodb.com/manual/core/inmemory/)

I have no experience with databases  :(

**Comment by alexec** [comment]
We use Mongo, but I think this was overkill. Writing to a disk would probably work just as well.

**Comment by rmannibucau** [comment]
Was thinking to orientdb or alike, mongo is clearly overkill and too heavy for that need.

**Comment by edumco** [comment]
@rmannibucau I've just runned orientdb and it was really fast. What do we need to change to make it work?

**Comment by rmannibucau** [comment]
Implement OrientDBDataStorage? (https://github.com/intuit/maven-build-scanner/blob/master/src/main/java/com/intuit/maven/extensions/build/scanner/infra/DataStorage.java) and make LifecycleProfiler not hardcode mongo impl by using a maven properties (better than using env var since maven properties can be populated from env but also system props.

**Comment by edumco** [comment]
@alexec Just clarifying if i really Understood the @rmannibucau comment

1. Create a class OrientDBDataStorage that implements the interface DataStorage
2. Alter the constructor of LifecycleProfiler to choose the database from a maven propertie
3. Create some unit testes to make sure nothing has stop working

What am I missing?

**Comment by alexec** [comment]
Would it possible to use files?

**Comment by alexec** [comment]
I'm refreshing my memory - I think the challenge isn't the Java code - but the Node code. I think there is a lot of logic there, e.g.

https://github.com/intuit/maven-build-scanner/blob/master/server/routes/index.js#L3

**Comment by alexec** [comment]
https://github.com/intuit/maven-build-scanner/blob/master/server/models/ProjectSummary.js#L1

**Comment by rmannibucau** [comment]
@edumco yep exactly.
@alexec orientdb is able to use files as well but supports in memory storage. Orientdb has a node driver btw: https://orientdb.com/docs/3.0.x/orientjs/OrientJS.html.

**Comment by alexec** [comment]
I think we can get rid of Mongo AND Node completely. Most of the logic is in JavaScript. 

You could implement DataStorage to output a small website:

```
~/.maven-build-scanner/project_summaries/{groupId}-{artifactId}
~/.maven-build-scanner/session_summaries/{id}
~/.maven-build-scanner/index.html
````

**Comment by edumco** [comment]
i did not understood. Instead of save to memory we would save to a html+js file?

**Comment by alexec** [comment]
Essentially we'd save a small static website.
