### ISSUE TITLE
SLF4J compatibity issues - logs not streaming while mvn target execution

### ISSUE THREAD

**Issue by pt-bhavsar** [intuit/maven-build-scanner#155]
Hello,

This is an amazing tool. Here is something happened post installation and I believe it may have to do with different running versions of SLF4J.

Set up:

OS - MAC
Maven Version - 3.8.6
Java Version - OpenJDK 11

For every mvn target execution, I don't see the log which I was able to see before. I see below:

`SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
SLF4J: Class path contains SLF4J bindings targeting slf4j-api versions 1.7.x or earlier.
SLF4J: Ignoring binding found at [jar:file:/opt/apache-maven-3.8.6/lib/maven-slf4j-provider-3.8.6.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See https://www.slf4j.org/codes.html#ignoredBindings for an explanation.`

I have tried to locate the culprit dependency, but I couldn't. Executing `mvn dependency:tree` also throw above warning.

Any insight in to fixing this? Thanks in advance

**Comment by pt-bhavsar** [comment]
Yeah it is working. No issues with build. I am not sure what got changed after the install. I lost the ability to see any meaningful mvn execution logs.

**Comment by artemgmiro** [comment]
removing `org.slf4j.slf4j-api` and `org.slf4j.slf4j-simple` from pom.xml helped to get back the maven logs

**Comment by gorohovart** [comment]
removing `org.slf4j.slf4j-api` and `org.slf4j.slf4j-simple` from pom.xml helped to get back the maven logs
