### ISSUE TITLE
Release version process 

### ISSUE THREAD

**Issue by edumco** [intuit/maven-build-scanner#16]
What do you think about create a release processes?

I can help with the automation.

**Comment by alexec** [comment]
This sounds good . Would you like to submit a PR? We can use Github Actions.

**Comment by juju2112** [comment]
If the jar were published, we could define it in an xml file in our project using [Core Extensions](http://takari.io/2015/03/19/core-extensions.html).

**Comment by StefanPenndorf** [comment]
As a workaround you can `mvn install` the project into your local `.m2` repository and use Core Extensions for the SNAPSHOT version built. But having the extension in maven central would of course be much better.

**Comment by edumco** [comment]
Started by updating the build on Github Actions on PR #31
