### ISSUE TITLE
com.intuit.maven.extensions.build.scanner.LifecycleProfiler error for custom application

### ISSUE THREAD

**Issue by jack-manju** [intuit/maven-build-scanner#23]
Hello,
I came across maven-build-scanner github repo. I tried to use maven scanner and followed Readme instruction.
When I m trying to run scanner for my custom application it is giving below error.

![image](https://user-images.githubusercontent.com/16605073/102007791-fa8b2380-3d51-11eb-9aaa-abf4f3636e6c.png)

**Comment by edumco** [comment]
@jack-manju Could you add the whole log?
