### ISSUE TITLE
setup.sh fails

### ISSUE THREAD

**Issue by schulm** [intuit/maven-build-scanner#28]
Was running setup.sh it fails with:
``
>>> 3/5 Building web server <<<
npm ERR! code E403
npm ERR! 403 403 Forbidden - GET https://registry.npmjs.intuit.com:443/artifactory/api/npm/npm-intuit/xdg-basedir/-/xdg-basedir-3.0.0.tgz
npm ERR! 403 In most cases, you or one of your dependencies are requesting
npm ERR! 403 a package version that is forbidden by your security policy, or
npm ERR! 403 on a server you do not have access to.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\xxxxx\AppData\Local\npm-cache\_logs\2021-03-25T11_44_35_458Z-debug.log
``

**Comment by aSemy** [comment]
I just had this problem. I fixed it by adding `npm update` to `setup.sh`

```
status "3/5 Building web server"
npm update
npm install
```

**Comment by alexec** [comment]
would you like to submit a PR?
