### ISSUE TITLE
Build failure - needs Java 11

### ISSUE THREAD

**Issue by alexec** [intuit/maven-build-scanner#33]
Failed to execute goal com.coveo:fmt-maven-plugin:2.10:format (default) on project maven-build-scanner: Execution default of goal com.coveo:fmt-maven-plugin:2.10:format failed: An API incompatibility was encountered while executing com.coveo:fmt-maven-plugin:2.10:format: java.lang.UnsupportedClassVersionError: com/google/googlejavaformat/java/FormatterException has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0

**Comment by edumco** [comment]
Is fixed by PR #35
