### ISSUE TITLE
Unable to use the extension (jdk11)

### ISSUE THREAD

**Issue by Boyman10** [intuit/maven-build-scanner#55]
After successfully building the application, I end up with the proper jar within :
/.m2/repository/com/intuit/maven-build-scanner/1.0.0-SNAPSHOT/maven-build-scanner-1.0.0-SNAPSHOT-jar-with-dependencies.jar

But while running the scan on a project after adding the .mvn/extensions.xml file - no report is being built.

I use jdk11 & maven 3.6.3

I might try a few things later and let you know.

**Comment by edumco** [comment]
@Boyman10 Thanks for reporting this issue. I would need more info to reproduce this issue:
- Operating System (distro and version)
- JDK distribution: Openjdk, Oracle ... 
- Maybe some log (mvn build -X ... )
- The problem only happens on compose?

**Comment by Boyman10** [comment]
Hi @edumco , thanks for your answer.

I got it running using the jdk8 (I don't know if having the extension built with jdk11 works with a jdk8 project...).

Using jdk 11 I can see those warnings at build time :
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/usr/share/maven/lib/guice.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```
I have no other logs, I only can say it does not display the Open url at the end of the project build and it also happens without compose.

I'm using jdk-11.0.7+10 from openJdk
on Linux  5.4.0-72-generic #80-Ubuntu

**Comment by edumco** [comment]
@Boyman10 thank you for the information. I've reproduced the problem and in my machine the folder 'ext' under 'lib' does not exist!

I'll mess around a little more

Apache Maven 3.6.3
Maven home: /usr/share/maven
Java version: 11.0.11, vendor: Ubuntu, runtime: /usr/lib/jvm/java-11-openjdk-amd64
Default locale: pt_BR, platform encoding: UTF-8
OS name: "linux", version: "5.8.0-50-generic", arch: "amd64", family: "unix"

**Comment by edumco** [comment]
I have found a temporary solution

On `setup.sh` on line 18 remove the `ext/` folder at the end of line

From:
```bash
18   .../lib/ext/
```
 To:
```bash
18   .../lib/
```

**Comment by edumco** [comment]
@Boyman10 the work around solved your problem?
